### ISSUE TITLE
How to handle StringSelectInteraction

### ISSUE THREAD

**Issue by juferdinand** [viascom/aluna-spring-boot-starter#160]
Hey I try to implement an Select on my Discord Bot but it doesnt work with Aluna for me.

Do I anything forget? Because their is no example for Buttons, Selects or something else.

This is my Code, hopefully u can help me :)

    override fun execute(event: SlashCommandInteractionEvent) {
        val gameOptions: List<SelectOption> = gameRepository.findAll().stream()
            .map { game -> SelectOption.of(game.gameName, game.gameId.toString()) }
            .collect(Collectors.toList())

        val gamesMenu = StringSelectMenu.create("games-menu")
            .setPlaceholder("Wähle Spiele für die Abstimmung")
            .addOptions(gameOptions)
            .build()

        event.reply("Wähle Spiele für die Abstimmung:")
            .addActionRow(gamesMenu)
            .queue()
    }
    override fun onStringSelectInteraction(event: StringSelectInteractionEvent): Boolean {
        val selectedGameId = event.selectedOptions[0].value

        // Hinzufügen des ausgewählten Spiels zum Voting
        // ...

        // Optionen für weitere Aktionen anbieten
        event.reply("Möchtest du ein weiteres Spiel hinzufügen oder das Voting starten?")
            .addActionRow(
                Button.primary("add-more", "Weiteres Spiel hinzufügen"),
                Button.success("start-voting", "Voting starten")
            )
            .setEphemeral(true)
            .queue()
        return true
    }

**Comment by itsmefox** [comment]
Hi

If you want that Aluna triggers your code when an interaction happens, you have to use `queueAndRegisterInteraction()` as described in the README here: https://github.com/viascom/aluna-spring-boot-starter?tab=readme-ov-file#react-to-a-button

Just make sure to select all the interaction types, Aluna should listen for.

**Comment by juferdinand** [comment]
Thx for the fast response, but I dont see how u get the hook. I tried by myself to get the hook from SlashCommandInteractionEvent but still it doesnt work, maybe u have some more docs or hints for me. This looks like this:

    override fun execute(event: SlashCommandInteractionEvent) {
        val gameOptions: List<SelectOption> = gameRepository.findAll().stream()
            .map { game -> SelectOption.of(game.gameName, game.gameId.toString()) }
            .collect(Collectors.toList())

        val gamesMenu = StringSelectMenu.create("games-menu")
            .setPlaceholder("Wähle Spiele für die Abstimmung")
            .addOptions(gameOptions)
            .build()

        event.reply("Wähle Spiele für die Abstimmung:")
            .setActionRow(gamesMenu)
            .queueAndRegisterInteraction(event.hook, this)
    }

**Comment by itsmefox** [comment]
For your use-case where you don't have an InteractionHook, you can use one of the overrides of `queueAndRegisterInteraction()`. 
The method you can use can be found [here](https://github.com/viascom/discord-bot-spring-boot-starter/blob/25f598d6ed0fb15d5587d33860020ca8e8ed7947/src/main/kotlin/io/viascom/discord/bot/aluna/bot/DiscordBot.kt#L824-L824). This method takes a DiscordInteractionHandler (the interface every Aluna DiscordCommand is based on), and no hook is needed.

_As I mentioned, you need to define the type Aluna should listen for. By default, only button interactions are watched for. I also included this in the example below._
```kotlin
event.reply("Wähle Spiele für die Abstimmung:")
            .setActionRow(gamesMenu)
            .queueAndRegisterInteraction(this, arrayListOf(EventRegisterType.STRING_SELECT))
```

_P.S. You only get an InteractionHook when you have already answered the command (Discord gives every application 3 seconds to acknowledge the request. If this does not happen, the user will see an error message.). As soon as you send the initial answer, you get a hook which can be used to update the message._

**Comment by juferdinand** [comment]
Thx alot I understand this now. Its very simple, I like your lib currently very much. 

Thank you for your hard work on this lib :)
